import * as time from "./time";
import * as countDown from "./count-down";
declare const _default: {
    debounce(hookHandler: Function, delay?: number, bindContext?: boolean): Function;
    throttle(hookHandler: Function, delay?: number, bindContext?: boolean): Function;
    hook(context: any, cb: any, args?: any[]): any;
    each(obj: any, cb: Function, isReturn?: boolean): void | any[];
    deepCopy(value: any): any;
    extend(...args: any[]): any;
    genGuid(): string;
    objectToArray<V>(object: {
        [key: string]: V;
    }): V[];
    arrayToObject<Item, Key extends keyof Item>(array: Item[], key: Key): { [key in keyof Item]?: Item; };
    getObjLen(object: any): number;
    getObjKeys(object: any): void | any[];
    promise(hookHandler: Function): Promise<any>;
    getRegExp(expr: any): string;
    prefixZero(number: number): string;
    genCountDownViewDate(diffTime: number): {
        day: string;
        hours: string;
        minutes: string;
        second: string;
    };
    formatDate(date: string | number | Date, format?: string): string;
    getDate(date?: string | number | Date): time.TResultDate;
    getYear(time?: string | number | Date): number;
    getMonth(time?: string | number | Date): number;
    getDay(time?: string | number | Date): number;
    getHours(time?: string | number | Date): number;
    getMinutes(time?: string | number | Date): number;
    getSeconds(time?: string | number | Date): number;
    getTime(time?: string | number | Date): number;
    timestamp(time: string | number | Date): number;
    diffTime(opts: {
        currentTime: string | number | Date;
        targetTime: string | number | Date;
        diffTime: number;
        condition: ">" | ">=" | "<" | "<=";
    }): boolean;
    CountDown: typeof countDown.CountDown;
    getLinkParams(link: string): string;
    getNotParamsLink(link?: string): string;
    parseParams(queryString: string, decode?: boolean): any;
    stringifyParams(query: any, encode?: boolean): string;
    isEmptyPlainObject(value: any): boolean;
    isStr(value: any): boolean;
    isPlainObject(value: any): boolean;
    isArray(value: any): boolean;
    isObject(value: any): boolean;
    isDef(value: any): boolean;
    isUndef(value: any): boolean;
    isEmptyStr(value: string): boolean;
    isTrue(value: any): boolean;
    isFalse(value: any): boolean;
    isFunction(value: any): boolean;
    isError(value: any): boolean;
    isBoolean(value: any): boolean;
};
export default _default;
